version: '3'

services:
  database:
    container_name: database
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - mynetwork
    volumes:
      - pgdata:/var/lib/postgresql/data

networks:
  mynetwork:
    driver: bridge

volumes:
  pgdata:
